workflows:
  ios-capacitor:
    name: iOS Capacitor Build (signed)
    max_build_duration: 60

    environment:
      node: 18
      xcode: latest

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.bauqontrol.app

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Build web assets
        script: |
          npm run build || echo "no build step"

      - name: Add iOS platform
        script: |
          npx cap add ios || true

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Apply provisioning profiles to Xcode project
        script: |
          # Wichtig: explizit euer Projekt angeben, damit Codemagic nicht irgendwo anders Signings setzt
          xcode-project use-profiles --project ios/App/App.xcodeproj

      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "ios/App/App.xcworkspace" \
            --scheme "App"

    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
